baseurl: "/"
languageCode: ja
title: My Web Site
theme: "hugo-tranquilpeak-theme"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
    - weight: 1
      name: TOP
      url: /
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
    - weight: 0
      name: About-自己紹介
      url: /about/
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-user\"></i>"
    - name: CV-足跡
      url: /CV/
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-file\"></i>"
    - name: Class-講義用
      url: /class/
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-graduation-cap\"></i>"
    - name: GitHub-共有用
      url: https://github.com/TIsh0321/my_blog.git
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
    - name: Twitter-つぶやき
      url: https://twitter.com/Isshii20
      pre: "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: "/favicon.icon"
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 100
    url: logo.png
    width: 100
  sidebarBehavior: 1
  thumbnailImage : true
  thumbnailImagePosition : "left"
  autoThumbnailImage : true
  coverImage : "images/cover.jpg"
  imageGallery : true
  hierarchicalCategories : true
  syntaxHighlighter : 'highlight.js'
social:
  -github: "TIsh0321/my_blog"